# Generated by Django 3.1.4 on 2020-12-26 10:54

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='subscriptions',
            fields=[
                ('slug', models.AutoField(primary_key=True, serialize=False)),
                ('slug_ref', autoslug.fields.AutoSlugField(editable=False, populate_from='slug')),
                ('made_afm', models.CharField(max_length=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default='False')),
                ('google_location', models.CharField(max_length=30)),
                ('notes', models.TextField(max_length=300)),
                ('resolve_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.services')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
