# Generated by Django 3.1.4 on 2020-12-26 19:22

import autoslug.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='crew',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug_ref', autoslug.fields.AutoSlugField(editable=False, populate_from='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('working_hours', models.CharField(max_length=30)),
                ('crew_members', models.TextField(max_length=30)),
                ('complains_id', models.TextField(max_length=330)),
                ('total_assigments', models.CharField(max_length=6)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
