# Generated by Django 3.1.4 on 2020-12-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_crew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='subscription_id',
        ),
    ]
