# Generated by Django 3.1.4 on 2020-12-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_subscriptions_subscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='resolve_date',
        ),
    ]
