# Generated by Django 3.1.4 on 2020-12-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_subscriptions_resolve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='citypart',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='subaddress',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
