# Generated by Django 3.1.7 on 2021-03-31 22:18

import autoslug.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201227_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('slug', models.AutoField(primary_key=True, serialize=False)),
                ('slug_ref', autoslug.fields.AutoSlugField(editable=False, populate_from='slug')),
                ('afm', models.CharField(default=None, max_length=30)),
                ('amka', models.CharField(default=None, max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(default=None, max_length=30)),
                ('phone', models.CharField(default=None, max_length=30)),
                ('iban', models.CharField(default=None, max_length=30)),
                ('name', models.CharField(default=None, max_length=30)),
                ('mail', models.CharField(default=None, max_length=30)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='exchange',
            fields=[
                ('slug', models.AutoField(primary_key=True, serialize=False)),
                ('slug_ref', autoslug.fields.AutoSlugField(editable=False, populate_from='slug')),
                ('afm', models.CharField(default=None, max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=255)),
                ('retailerafm', models.CharField(max_length=255)),
                ('profit', models.CharField(max_length=255)),
                ('gave', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='exchanges',
            fields=[
                ('slug', models.AutoField(primary_key=True, serialize=False)),
                ('slug_ref', autoslug.fields.AutoSlugField(editable=False, populate_from='slug')),
                ('afm', models.CharField(default=None, max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=255)),
                ('retailerafm', models.CharField(max_length=255)),
                ('profit', models.CharField(max_length=255)),
                ('gave', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='helpdesk',
            fields=[
                ('slug', models.AutoField(primary_key=True, serialize=False)),
                ('slug_ref', autoslug.fields.AutoSlugField(editable=False, populate_from='slug')),
                ('useruuid', models.CharField(max_length=128)),
                ('lastlog', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug_ref', autoslug.fields.AutoSlugField(editable=False, populate_from='UUID')),
                ('type', models.CharField(max_length=30)),
                ('buyingprice', models.CharField(max_length=255)),
                ('sellingprice', models.CharField(max_length=255)),
                ('profit', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('weight', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='materials',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug_ref', autoslug.fields.AutoSlugField(editable=False, populate_from='UUID')),
                ('type', models.CharField(max_length=30)),
                ('buyingprice', models.CharField(max_length=255)),
                ('sellingprice', models.CharField(max_length=255)),
                ('profit', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('weight', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='officialretailer',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('storename', models.CharField(max_length=30)),
                ('storetype', models.CharField(max_length=30)),
                ('producttype', models.CharField(max_length=30)),
                ('afm', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='otinanai',
            fields=[
                ('slug', models.AutoField(primary_key=True, serialize=False)),
                ('slug_ref', autoslug.fields.AutoSlugField(editable=False, populate_from='slug')),
                ('useruuid', models.CharField(max_length=128)),
                ('lastlog', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='retailer',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('storename', models.CharField(max_length=30)),
                ('storetype', models.CharField(max_length=30)),
                ('producttype', models.CharField(max_length=30)),
                ('afm', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('slug', models.AutoField(primary_key=True, serialize=False)),
                ('slug_ref', autoslug.fields.AutoSlugField(editable=False, populate_from='slug')),
                ('afm', models.CharField(default=None, max_length=30)),
                ('amka', models.CharField(default=None, max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(default=None, max_length=30)),
                ('phone', models.CharField(default=None, max_length=30)),
                ('iban', models.CharField(default=None, max_length=30)),
                ('name', models.CharField(default=None, max_length=30)),
                ('mail', models.CharField(default=None, max_length=30)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.DeleteModel(
            name='crew',
        ),
        migrations.DeleteModel(
            name='services',
        ),
        migrations.DeleteModel(
            name='subscriptions',
        ),
    ]
