# Generated by Django 3.1.7 on 2021-03-31 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210331_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customers',
        ),
        migrations.DeleteModel(
            name='exchanges',
        ),
        migrations.DeleteModel(
            name='materials',
        ),
        migrations.DeleteModel(
            name='officialretailer',
        ),
        migrations.DeleteModel(
            name='otinanai',
        ),
    ]
