# Generated by Django 3.1.7 on 2021-03-31 22:31

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210331_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginlogs',
            fields=[
                ('slug', models.AutoField(primary_key=True, serialize=False)),
                ('slug_ref', autoslug.fields.AutoSlugField(editable=False, populate_from='slug')),
                ('afm', models.CharField(default=None, max_length=30)),
            ],
        ),
    ]
