# Generated by Django 3.1.7 on 2021-03-31 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_loginlogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginlogs',
            old_name='afm',
            new_name='uuid',
        ),
    ]
